export { default as EnvelopeIcon } from 'material-ui/svg-icons/content/drafts'
export { default as HistoryIcon } from 'material-ui/svg-icons/action/history'
export { default as AnalyzeIcon } from 'material-ui/svg-icons/action/timeline'
export { default as CollaborateIcon } from 'material-ui/svg-icons/social/people'
export { default as FeedbackIcon } from 'material-ui/svg-icons/action/feedback'
export { default as CodeIcon } from 'material-ui/svg-icons/action/code'
